[features]
seeds = false
skip-lint = false
[programs.devnet]
myepicproject = "EifYvJyprCavJ9WmCUXWprQxmBV23sjacqWBmAvJEUSi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/akihi-sumi/.config/solana/devnet.json"

[scripts]
test = "node tests/myepicproject.js"
